using KeyboardHookReceiver.Dto;
using KeyboardHookReceiver.Models;
using Npgsql;

namespace KeyboardHookReceiver.Repository;

public class Repository : IRepository
{
    private readonly string _connectionString;

    public Repository(string connectionString)
    {
        _connectionString = connectionString;
    }

    public async Task CreateTableByAccountNameAsync(string accountName)
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = new NpgsqlCommand { Connection = conn };

        cmd.CommandText = $"CREATE TABLE IF NOT EXISTS {accountName} " +
                          "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                          "datetime timestamp," +
                          "program varchar," +
                          "keyCode smallint," +
                          "click varchar(30))";

        await cmd.ExecuteNonQueryAsync();

        await conn.CloseAsync();
    }

    public async Task AddKeyboardLogToTableAsync(KeyboardInputDto log)
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = new NpgsqlCommand
        {
            Connection = conn,
            CommandText = $"INSERT INTO {log.AccountName} (datetime, program, keyCode, click) " +
                          $"VALUES ('{log.DateTime}', '{log.Program}', '{log.KeyCode}', null)"
        };

        await cmd.ExecuteNonQueryAsync();

        await conn.CloseAsync();
    }

    public async Task AddMouseLogToTableAsync(MouseClickPosInputDto log)
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = new NpgsqlCommand { Connection = conn };

        cmd.CommandText = $"INSERT INTO {log.AccountName} (datetime, program, keyCode, click) " +
                          $"VALUES ('{log.DateTime}', '{log.Program}', null, '{log.clickSide}Click [x:{log.X}, y:{log.Y}]')";

        await cmd.ExecuteNonQueryAsync();

        await conn.CloseAsync();
    }

    public async Task<ICollection<InputAction>> GetActionsByAccountInTimeInterval(
        string accountName,
        DateTime from,
        DateTime until)
    {
        await using var conn = new NpgsqlConnection(_connectionString);
        await conn.OpenAsync();

        await using var cmd = new NpgsqlCommand { Connection = conn };

        cmd.CommandText = $"SELECT * FROM {accountName} a " +
                          $"WHERE a.datetime >= '{from}' AND a.datetime <= '{until}'";

        var actions = new List<InputAction>();
        await using (var reader = await cmd.ExecuteReaderAsync())
        {
            while (await reader.ReadAsync())
            {
                for (var i = 0; i < reader.FieldCount - 1; i += 5)
                {
                    actions.Add(new InputAction
                    {
                        Id = reader.GetInt32(0),
                        DateTime = reader.GetDateTime(i + 1),
                        Program = reader.GetString(i + 2),
                        KeyCode = reader.IsDBNull(i + 3) ? 0 : reader.GetInt16(i + 3),
                        Click = reader.IsDBNull(i + 4) ? null : reader.GetString(i + 4)
                    });
                    Console.WriteLine();
                }
            }
        }

        await conn.CloseAsync();

        return actions;
    }
}